export const StackNav = {
  Auth: 'Auth',
  Splash: 'Splash',
  WelcomeScreen: 'WelcomeScreen',
  HomeTab:'HomeTab',
  AudioFiles: 'AudioFiles',
  ListScreen:'ListScreen',
  DetailScreen: 'DetailScreen',
  Music: 'Music',
  About: 'About',
  WahdatulWujud:'WahdatulWujud',
  GnanaAgamiyas:'GnanaAgamiyas',
  Books:'Books',
  Programs:'Programs',
  Education:'Education',
  Manitha:'Manitha',
  Collections:'Collections',
  EmsDetailScreen:'EmsDetailScreen',
  Quiz:'Quiz',
  PhotoGallery:'PhotoGallery',
  VideoGallery: 'VideoGallery',
  AudioGallery: 'AudioGallery',
  Login: 'Login',
  SignUp:'SignUp',
  ForgotPass:'ForgotPass',
  LogOutPage:'LogOutPage',
  CreateNewPassword:'CreateNewPassword',
  PlayAudio:'PlayAudio',
  ProductList:'ProductList',
  ProductViewCart:'ProductViewCart',
  PaymentSelect:'PaymentSelect',
  ProductAddCart:'ProductAddCart',
  Magazine:'Magazine',
  Event:'Event',
  Payment:'Payment',
  Articles:'Articles',
  Profile:'Profile',
  PlayAudioGallery:'PlayAudioGallery',
  SchemeDetail:'SchemeDetail',
};
